# Assignment 3(1)

## Task 1

1) Write a function to compute 5/0 and use try/except to catch the exceptions.

In [8]:
def div_by_zero():
    return 5/0

try:
    div_by_zero()
#except ZeroDivisionError as z:
#    print("Error occured: ", z)
except Exception as e:
    print("Error occured in the code: ", e)
    
    

Error occured in the code:  division by zero


2) Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [8]:
subjects=["Americans", "Indians"]
verbs=["Play", "watch"]
objects=["Baseball","cricket"]

sentences = [(x+" "+ y + " " + z) for x in subjects for y in verbs for z in objects]
for i in sentences:
    print (i)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


## Task 2

1) Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [31]:
import numpy as np
 
def vandermonde(input_array, n, increasing):
    
    if increasing==False:
        output = np.array([m**(n-1-i) for m in input_array for i in range(n)])
    elif increasing==True:
        output = np.array([m**i for m in input_array for i in range(n)])
    
    return output.reshape(input_array.size,n)

input_a = np.array([1,2,3,4,5,6])
no_col = 4
output_decrease = vandermonde(input_a,no_col,False)
output_increase = vandermonde(input_a,no_col,True)

print("Input array is:",input_a)
print("Number of columns:",no_col)
print("Power increase=False array:",'\n',output_decrease)
print("Power increase=True array:",'\n',output_increase)

Input array is: [1 2 3 4 5 6]
Number of columns: 4
Power increase=False array: 
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]]
Power increase=True array: 
 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   6  36 216]]


In [14]:
#column of the output matrix are power of the input vector
import numpy as np
x = np.array([1,2,3,4,5])
N = 4

np.vander(x,N)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])